### ISSUE TITLE
应用哪个大模型，就提前设置好该大模型对应的 API KEY  这个选项可以选择开源的大模型吗？比如glm和baichuan2-13B。可以的话，应该怎么选择

### ISSUE THREAD

**Issue by cristianohello** [52phm/pylmkit#1]
应用哪个大模型，就提前设置好该大模型对应的 API KEY

这个选项可以选择开源的大模型吗？比如glm和baichuan2-13B。可以的话，应该怎么选择

**Comment by 52phm** [comment]
最新版本0.0.13版本已增加支持本地开源模型下载和部署使用的功能，具体教程情况README.md，或者 http://zh.pylmkit.cn
